# Generated by Django 3.2.6 on 2021-08-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='age_group',
            field=models.CharField(choices=[['18to45', '18_TO_45'], ['45plus', '45_PLUS']], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='registration_id',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='slot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.slot'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('vaccine', 'date', 'slot', 'age_group')},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='token',
            name='date',
        ),
    ]
