# Generated by Django 3.2.6 on 2021-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20210810_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
