# Generated by Django 3.2.6 on 2021-08-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_slot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='checked',
            field=models.IntegerField(choices=[['yes', 1], ['no', 0]], default=0),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
