# Generated by Django 3.2.6 on 2021-08-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20210830_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created_by',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
