# Generated by Django 3.2.6 on 2021-09-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_token_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='created_at',
        ),
    ]
