# Generated by Django 3.2.6 on 2021-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20210911_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
