# Generated by Django 3.2.6 on 2021-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_remove_token_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='comorbidity_ind',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(choices=[['Male', 'Male'], ['Female', 'Female']], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo_id_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo_id_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='vaccination_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='vaccine',
            field=models.CharField(blank=True, choices=[['covishield', 'Covishield'], ['covaxin', 'Covaxin']], max_length=25, null=True),
        ),
    ]
