# Generated by Django 3.2.6 on 2021-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210810_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='dose1_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='dose2_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
