# Generated by Django 3.2.6 on 2021-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20210830_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='checked',
        ),
        migrations.AddField(
            model_name='token',
            name='checked',
            field=models.IntegerField(choices=[['yes', 1], ['no', 0]], default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
