# Generated by Django 3.2.6 on 2021-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_remove_beneficiary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='token',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='token',
            name='vaccine',
            field=models.CharField(choices=[['covishield', 'Covishield'], ['covaxin', 'Covaxin']], default='covishield', max_length=15),
        ),
    ]
