# Generated by Django 3.2.6 on 2021-09-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_token_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='availability',
        ),
    ]
