# Generated by Django 3.2.6 on 2021-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20210913_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='comorbidity_ind',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo_id_number',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo_id_type',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='vaccination_status',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
